{
 "title": "Linux Host's",
 "tags": [ "Linux" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DB", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=~\"integrations/(node_exporter|unix)\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Time Zone",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_zone_offset_seconds{job=\"integrations/unix\", instance=\"$instance\"}",
     "legendFormat": "{{time_zone}}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_os_info{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}\n"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without (cpu) (node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "title": "Kernel version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Time Sync",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_timex_sync_status{job=\"integrations/unix\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}",
     "legendFormat": "Memory total"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count by (instance) (count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}) by (cpu, instance))\n",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\", mode=~\"idle|iowait|steal\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\", mode=\"idle\"})\n) * 100\n",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "count without (cpu) (node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg by (instance) (node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}) /\n  avg by (instance) (node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}\n-\n  node_memory_MemFree_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}\n-\n  node_memory_Buffers_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}\n-\n  node_memory_Cached_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}\n)\n",
     "legendFormat": "Memory used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}",
     "legendFormat": "Memory cached"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}",
     "legendFormat": "Memory available"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}",
     "legendFormat": "Memory buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}",
     "legendFormat": "Memory free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\"}",
     "legendFormat": "Memory total"
    }
   ]
  },
  {
   "title": "Disk reads/writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\", device!=\"sr0\"}[$__rate_interval])",
     "legendFormat": "{{ device }} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\", device!=\"sr0\"}[$__rate_interval])",
     "legendFormat": "{{ device }} written"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\", device!=\"sr0\"}[$__rate_interval])",
     "legendFormat": "{{ device }} io util"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype!=\"\", mountpoint!=\"\", job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\",mountpoint!~\"/run.*\"}"
    },
    {
     "expr": "node_filesystem_avail_bytes{fstype!=\"\", mountpoint!=\"\", job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\",mountpoint!~\"/run.*\"}",
     "legendFormat": "{{ mountpoint }} free"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\",device!=\"lo\"}[$__rate_interval])*8\n# only show interfaces that had traffic change at least once during selected dashboard interval:\nand\nincrease(\n    node_network_receive_bytes_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\",device!=\"lo\"}[$__range]\n    ) > 0\n",
     "legendFormat": "{{ device }} received"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\",device!=\"lo\"}[$__rate_interval])*8\n# only show interfaces that had traffic change at least once during selected dashboard interval:\nand\nincrease(\n    node_network_transmit_bytes_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\",device!=\"lo\"}[$__range]\n    ) > 0\n",
     "legendFormat": "{{ device }} transmitted"
    }
   ]
  },
  {
   "title": "Network errors and dropped packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_errs_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\",device!=\"lo\"}[$__rate_interval])>0",
     "legendFormat": "{{ device }} errors transmitted"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\",device!=\"lo\"}[$__rate_interval])>0",
     "legendFormat": "{{ device }} errors received"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\",device!=\"lo\"}[$__rate_interval])>0",
     "legendFormat": "{{ device }} transmitted dropped"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=~\"integrations/(node_exporter|unix)\",instance=~\"$instance\",device!=\"lo\"}[$__rate_interval])>0",
     "legendFormat": "{{ device }} received dropped"
    }
   ]
  }
 ]
}